# Name: Zachary Neeley
# Lab: wordlength
# Date: 1/18/19
# Description: Using lex the makefile will compile wordlengthlab1.l to create the lex.yy.c
#	       then using the gcc compiler create an wordlength program.
#

all: 
	lex wordlengthlab1.l
	gcc -o wordlength lex.yy.c

