# Name: Zachary Neeley
# Lab: 2.1
# Date: 1/18/19
# Description: Using lex the makefile will compile wordlengthlab1.l to create the lex.yy.c
#	       then using the gcc compiler create an wordlength program.
#

all: 
	lex lab2remove.l
	gcc -o lab2 lex.yy.c

